/*
 * This file is generated by jOOQ.
 */
package com.example.app.jooq.model;


import com.example.app.jooq.model.tables.Game;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.game</code>.
     */
    public static final Game GAME = Game.GAME;
}
